services:
  rrobin:
      build: 
        context: .
        dockerfile: node.dockerfile
      ports:
          - "80:80"
      networks:
        ansible_net:
            ipv4_address: 172.20.0.10
  web1:
      build: 
        context: .
        dockerfile: node.dockerfile
      networks:
        ansible_net:
            ipv4_address: 172.20.0.11
  web2:
      build:
        context: .
        dockerfile: node.dockerfile
      networks:
        ansible_net:
            ipv4_address: 172.20.0.12

networks:
    ansible_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/24
